---
title: "Lab Scrum"
author: "Malcolm Barrett"
format: kakashi-revealjs
---

```{r setup, include=FALSE}
options(
  tibble.max_extra_cols = 6, 
  tibble.width = 60
)
```

## Meetings and scrum
- The goal of scrum is to improve and make visible all stages of work, not just outputs (as in traditional lab meetings)
- Scrum is a framework for organizing work, not a set of rules

## Regular, short checkups
- e.g, daily stand-ups 
- *improves*: feedback on work in progress, visibility, collaboration 

## Planning for defined periods
- e.g., sprint planning 
- *improves*: feedback on work plan, short-term goals, accountability 
- Research is a big project. It helps to have a clear sense of what to do next and to have a sense of progress.

## Presenting work
- e.g., traditional lab meetings, sprint demos/reviews 
- improves: feedback on work product, visibility via focused updates

## Improving team work process
- e.g., sprint retrospectives (what went well, what could be improved, what to try next)
- improves: feedback on work process, team agency over process
- continuous improvement. team agreements are living documents. 

## Resources {background-color="#23373B"}

### [Lab Scrum](https://labscrum.org/)

